package com.training.config.variable;

/**
 * Application constant
 * generated by initializr
 */
public class AppConstant {
    public static final String MESSAGE_OK = "Sukses";
    public static final String MESSAGE_FAILED = "Gagal";
    public static final String MESSAGE_NOT_FOUND = "Data tidak di temukan";
}
